services:

  fluxgym:
    build:
      context: .
      dockerfile: Dockerfile
    # image: d3smond/docker-fluxgym
    container_name: fluxgym
    ports:
      - 7860:7860
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data:/data
    stop_signal: SIGKILL
    tty: true
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    restart: unless-stopped
    #command: [ "/bin/bash", "-c", "--", "while true; do sleep 30; done;" ]

    command: [ "/bin/bash", "/setup/run.sh" ]